### ISSUE TITLE
doesn't work with redmine 4.1

### ISSUE THREAD

**Issue by shemgp** [everlabs/quick_issue#3]
```
/var/lib/gems/2.7.0/gems/activerecord-5.2.4.2/lib/active_record/type.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/activerecord-5.2.4.2/lib/active_record/type/adapter_specific_registry.rb:9: warning: The called method `add_modifier' is defined here
/var/lib/gems/2.7.0/gems/activerecord-5.2.4.2/lib/active_record/associations.rb:1855: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/activerecord-5.2.4.2/lib/active_record/associations.rb:1368: warning: The called method `has_many' is defined here
rake aborted!
NoMethodError: undefined method `alias_method_chain' for ProjectsHelper:Module
Did you mean?  alias_method
/usr/share/redmine/plugins/quick_issue/lib/quick_add_issue_helper_patch.rb:8:in `block in included'
/usr/share/redmine/plugins/quick_issue/lib/quick_add_issue_helper_patch.rb:7:in `class_eval'
/usr/share/redmine/plugins/quick_issue/lib/quick_add_issue_helper_patch.rb:7:in `included'
/usr/share/redmine/plugins/quick_issue/lib/quick_add_issue_helper_patch.rb:26:in `include'
/usr/share/redmine/plugins/quick_issue/lib/quick_add_issue_helper_patch.rb:26:in `<top (required)>'
/var/lib/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.7.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/usr/share/redmine/plugins/quick_issue/init.rb:1:in `<top (required)>'
/var/lib/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.7.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/usr/share/redmine/lib/redmine/plugin.rb:181:in `block in load'
/usr/share/redmine/lib/redmine/plugin.rb:172:in `each'
/usr/share/redmine/lib/redmine/plugin.rb:172:in `load'
/usr/share/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
/var/lib/gems/2.7.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
/var/lib/gems/2.7.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `block in load'
/var/lib/gems/2.7.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
/var/lib/gems/2.7.0/gems/railties-5.2.4.2/lib/rails/engine.rb:663:in `block in load_config_initializer'
/var/lib/gems/2.7.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
/var/lib/gems/2.7.0/gems/railties-5.2.4.2/lib/rails/engine.rb:662:in `load_config_initializer'
/var/lib/gems/2.7.0/gems/railties-5.2.4.2/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.7.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `each'
/var/lib/gems/2.7.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `block in <class:Engine>'
/var/lib/gems/2.7.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/2.7.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/2.7.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/2.7.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `each'
/var/lib/gems/2.7.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/var/lib/gems/2.7.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/2.7.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
/usr/share/redmine/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.7.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.7.0/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!'
/var/lib/gems/2.7.0/gems/railties-5.2.4.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by shemgp** [comment]
Thanks for looking into it.
